version: '3.7'

services:
  example-app:
    image: billsoum/example-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      BOOTSTRAP_SERVER: "kafka:9092"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9999/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9999:9999"
    expose:
      - 9999
    depends_on:
      - kafka
    networks:
      - kafka_net

networks:
  kafka_net:
    external: true